Members-only
yahir91/member-only pull request #1
Opened 2020-08-10 22:44 UTC by yahir91

In this project, we build a blog that members can create posts, and they can see who wrote the posts but the nonmembers can not see the author.

2020-08-11 10:54 UTC, stratospherique requested changes
### Great start @team :clap: :clap: However, some requirements need to be implemented in order to get approval for this milestone. Check :arrow_down: 

- **[REQUIRED]** The application has Sign in/Sign out links present in any view of the app ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/sign_in_out_link_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49722686/))
##### Routes
- **[REQUIRED]** It creates the application routes using `resources :posts, only: [:new, :create, :index]` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/posts_routes_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication)) 
##### Views
- **[REQUIRED]** There shoud be absolutely NO logic in views.
* [ ] View-related logic can be encapsulated in View helpers (app/helpers/\*_helper.rb)
  > Views are only for displaying information that became available to it from its corresponding controller not generating it. **Resources**
##### PostsController

- **[REQUIRED]** it uses `before_action` to restrict access to the `:new` and `:create` methods (uses ApplicationController helper method) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/before_action_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/authentication))
##### General
- **[REQUIRED]** Pull Request has a meaningful title and a brief description ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
### That's it :relieved: When finished, kindly submit a code re-review request :pray: 

Happy coding :v: 
**_Ahmed Mahfoudh_**

2020-08-12 11:27 UTC, stratospherique requested changes
### Great progress @team. :clap: However, some changes need to be applied in order to get approval for this project. Check :arrow_down: 

- **[REQUIRED]** The views still have logic in them. refer to the articles below, they should help you refactor your views
* [Where Do I Put My Code?](http://codefol.io/posts/Where-Do-I-Put-My-Code)
* [The Beginner's Guide to Rails Helpers](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers)
- **[REQUIRED]** Check the code comments below, they should help you make the necessary fixes to some issues that weren't fixed.
### That's it :relieved: When finished, kindly submit a code re-review request :pray: 

Happy coding :v: 
**_Ahmed Mahfoudh_**

2020-08-12 11:27 UTC, stratospherique commented on app/controllers/posts_controller.rb
> +  before_action :authenticate_member!, except: %i[index]
- authenticate_member! is repeated twice and assigned for actions other that new and create. Kindly remove the last one.

2020-08-12 11:27 UTC, stratospherique commented on config/routes.rb
> +  resources :members
- **[REQUIRED]** only routes that are used should be defined.

2020-08-12 11:27 UTC, stratospherique commented on app/controllers/posts_controller.rb
> +        format.json { render :show, status: :created, location: @post }
- Rendering unused JSON data can cause performance issues to the server in a production environment. Plus, you won't need it unless you have a front-end that will consume it Kindly remove all lines responsible for rendering JSON data.

2020-08-12 23:39 UTC, rOluochKe approved these changes
Hello @yahir91 and @maosan132 
### Well done, you got it right :clap: The project has been approved. Congratulations :boom: :100:
### Merge and submit the project. Good luck with the next project.
- Happy coding!

### Improvements
- [ ] Remove all the commented code
- [ ] You can use bare bootstrap to style the app that way it will look better and presentable

2020-09-16 22:05 UTC, merged